[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NODE_TLS_REJECT_UNAUTHORIZED = "0"

[functions]
  node_bundler = "esbuild"

[functions.environment]
  NODE_TLS_REJECT_UNAUTHORIZED = "0"

[[plugins]]
  package = "@netlify/plugin-nextjs"
